from typing import Annotated, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from tradingagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    risky_history: Annotated[
        str, "Risky Agent's Conversation history"
    ]  # Conversation history
    safe_history: Annotated[
        str, "Safe Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_risky_response: Annotated[
        str, "Latest response by the risky analyst"
    ]  # Last response
    current_safe_response: Annotated[
        str, "Latest response by the safe analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Crypto token symbol that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    technical_report: Annotated[str, "Report from the Technical Analyst"]
    onchain_report: Annotated[str, "Report from the Onchain Analyst"]
    tokenomics_report: Annotated[str, "Report from the Tokenomics Analyst"]
    sentiment_news_report: Annotated[str, "Report from the Sentiment/News Analyst"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]
    raw_confidence: Annotated[
        Optional[float],
        "Trader's self-reported confidence (0.0-1.0), parsed from its FINAL TRANSACTION "
        "PROPOSAL line via tradingagents.agents.utils.parsing.extract_confidence. "
        "None if the LLM didn't follow the required output format -- not a guessed value.",
    ]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]

    # Stage 4/5 (Alpha Illusion-mapped pipeline, draft.md Section 3.1) -- populated
    # post-hoc by the Reflection/ACE agent (tradingagents/agents/reflection/), not
    # by any in-graph node as of Week 16. Present in the schema now so Week 17
    # integration doesn't need to touch agent_states.py again.
    calibrated_probability: Annotated[
        Optional[float], "raw_confidence after Stage 4 statistical calibration"
    ]
    position_sizing: Annotated[
        Optional[dict], "Stage 5 deterministic sizing output (see tradingagents.calibration.sizing)"
    ]
